---
# Copyright 2017, Stackmasters.eu

- name: Stop httpd service
  service:
    name: httpd
    state: stopped
    enabled: yes
  tags:
    - upgrade-keystone

- name: Upgrade keystone packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - \*keystone\*
  tags:
    - upgrade-keystone

- name: Upgrade keystone packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - \*horizon\*
    - \*openstack-dashboard\*
    - \*python-django\*
  tags:
    - upgrade-keystone

- name: Upgrade openstack-selinux
  command: keystone-manage token_flush
  tags:
    - upgrade-keystone

- name: Upgrade the keystone database
  command: keystone-manage db_sync
  become: yes
  become_user: "{{ keystone_system_user_name }}"
  ignore_errors: yes
  tags:
    - upgrade-keystone
    - upgrade-keystone-db

- name: Start httpd service
  service:
    name: httpd
    state: started
    enabled: yes
  tags:
    - upgrade-keystone

