---
# Copyright 2017, Stackmasters.eu

- name: Stop Heat services
  command: openstack-service stop heat
  tags:
    - upgrade-heat

- name: Upgrade Heat packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - \*heat\*
  tags:
    - upgrade-heat

- name: Upgrade the Heat database
  command: heat-manage db_sync
  sudo: yes
  sudo_user: "{{ heat_system_user_name }}"
  ignore_errors: yes
  tags:
    - upgrade-heat
    - upgrade-heat-db

- name: Start Heat services
  command: openstack-service start heat
  tags:
    - upgrade-heat
