---
# Copyright 2016, Stackmasters.eu

- name: Create Glance user
  os_user:
    state: present
    name: "{{ glance_service_user_name }}"
    password: "{{ glance_service_user_pass }}"
    domain: "{{ glance_service_user_domain_id }}"
    default_project: "{{ glance_service_project_name }}"
    region_name: "{{ glance_service_region }}"
    auth: auth_url=http://{{ internal_vip }}:35357/v3 username=admin password={{ keystone_admin_user_password }}
  tags:
    - glance-service

- name: Assosiate Glance user with admin role
  os_user_role:
    user: "{{ glance_service_user_name }}"
    role: "{{ glance_service_role_name }}"
    project: "{{ glance_service_project_name }}"
    auth: auth_url=http://{{ internal_vip }}:35357/v3/ username=admin password={{ keystone_admin_user_password }}
  tags:
    - glance-service

- name: Check if Glance service is present
  shell: source /root/openrc && openstack service list
  register: glance_service
  tags:
    - glance-service

- name: Create glance service entity
  shell: source /root/openrc && openstack service create --name {{ glance_service_user_name }} \
           --description "OpenStack Image service" image
  when: "glance_service.stdout.find('glance') == -1"
  tags:
    - glance-service

- name: Check if glance endpoints are present
  shell: source /root/openrc && openstack endpoint list
  register: glance_endpoint
  tags:
    - glance-service
    - glance-endpoint

- name: Create glance service endpoint
  shell: source /root/openrc && openstack endpoint create --region {{ glance_service_region }} image {{ item.key }} "http://{{ item.value }}:9292"
  when: "glance_endpoint.stdout.find('glance') == -1"
  with_items:
    - { key: "public", value: "{{ external_vip }}" }
    - { key: "internal", value: "{{ internal_vip }}" }
    - { key: "admin", value: "{{ internal_vip }}" }
  tags:
    - glance-service
    - glance-endpoint
