---
# Copyright 2016, Stackmasters.eu

- name: Create glance database
  mysql_db:
    name: "{{item}}"
    state: present
    login_host: "{{ groups['galera'][0] }}"
    login_user: root
    login_password: "{{ galera_root_pass }}"
  with_items:
    - "{{ glance_db_name }}"
  tags:
    - glance-db-setup

- name: Create glance db user
  mysql_user:
    state: present
    name: "{{ glance_db_user }}"
    host: "{{ item }}"
    priv: "{{ glance_db_name }}.*:ALL"
    password: "{{ glance_db_pass }}"
    login_host: "{{ groups['galera'][0] }}"
    login_user: root
    login_password: "{{ galera_root_pass }}"
  with_items:
    - "localhost"
    - "%"
  tags:
    - glance-db-setup


- name: Perform a Glance DB sync
  command: glance-manage db_sync
  become: yes
  become_user: "{{ glance_system_user }}"
  with_items:
    - "{{  glance_db_name }}"
  tags:
    - glance-db-setup
    - glance-setup
