---
# Copyright 2016, Stackmasters.eu

- name: Ensure Rabbitmq vhost
  rabbitmq_vhost:
    name: "{{ nova_rabbitmq_vhost }}"
    state: "present"
  delegate_to: "{{ groups['rabbitmq'][0] }}"
  tags:
    - nova-rabbitmq
    - nova-rabbitmq-vhost

- name: Ensure rabbitmq user
  rabbitmq_user:
    user: "{{ nova_rabbitmq_user }}"
    password: "{{ nova_rabbitmq_pass }}"
    vhost: "{{ nova_rabbitmq_vhost }}"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: "present"
  delegate_to: "{{ groups['rabbitmq'][0] }}"
  tags:
    - nova-rabbitmq
    - nova-rabbitmq-user
