---
# Copyright 2016, Stackmasters.eu

- name: Create nova databases
  mysql_db:
    name: "{{item}}"
    state: present
    login_host: "{{ groups['galera'][0] }}"
    login_user: root
    login_password: "{{ galera_root_pass }}"
  with_items:
    - "{{ nova_db_name }}"
    - "{{ nova_api_db_name }}"
  tags:
    - nova-db-setup

- name: Create nova db user
  mysql_user:
    state: present
    name: "{{ nova_db_user }}"
    host: "{{ item }}"
    priv: "{{ nova_db_name }}.*:ALL/{{ nova_api_db_name }}.*:ALL"
    password: "{{ nova_db_pass }}"
    login_host: "{{ groups['galera'][0] }}"
    login_user: root
    login_password: "{{ galera_root_pass }}"
  with_items:
    - "localhost"
    - "%"
  tags:
    - nova-db-setup

- name: Perform a Nova DB sync
  command: nova-manage {{ item }} sync
  sudo: yes
  sudo_user: "{{ nova_system_user }}"
  with_items:
    - "api_db"
    - "db"
  tags:
    - nova-db-setup
    - nova-db-sync
