---
# Copyright 2016, Stackmasters.eu

- name: Check if nova secret is defined in libvirt
  shell: virsh secret-list | grep {{ nova_ceph_uuid }}
  when: inventory_hostname in groups.nova_compute
  always_run:   true
  failed_when:  false
  changed_when: false
  register: libvirt_nova_defined
  tags:
    - nova-ceph-secret


- name: Retrieve nova secret from ceph cluster
  command: ceph auth get-key client.{{ nova_ceph_client }}
  when: inventory_hostname in groups.nova_compute
  register: ceph_client_nova_secret
  always_run:   true
  changed_when: false
  failed_when:  false
  register: ceph_nova_secret
  tags:
    - nova-ceph-secret

- name: Check if nova secret value is set in libvirt
  command: virsh secret-get-value {{ nova_ceph_uuid }}
  when: inventory_hostname in groups.nova_compute
  always_run:   true
  failed_when:  false
  changed_when: false
  register: libvirt_nova_set
  tags:
    - nova-ceph-secret

- name: Provide xml file to create the secret
  template:
    src: secret.xml.j2
    dest: /tmp/nova-secret.xml
  when: inventory_hostname in groups.nova_compute
  tags:
    - nova-ceph-secret

- name: Define libvirt nova secret
  command: virsh secret-define --file /tmp/nova-secret.xml
  when: inventory_hostname in groups.nova_compute
  tags:
    - nova-ceph-secret

- name: Set nova secret value in libvirt
  shell: virsh secret-set-value --secret {{ nova_ceph_uuid }} --base64 {{ ceph_nova_secret.stdout }}
  when: >
        inventory_hostname in groups.nova_compute and libvirt_nova_set.rc is defined
        and
        (libvirt_nova_set.rc != 0
        or
        (libvirt_nova_set.rc == 0 and libvirt_nova_set.stdout != ceph_nova_secret.stdout)
        )
  tags:
    - nova-ceph-secret

