---
# Copyright 2016, Stackmasters.eu

# Hypervisor type
nova_hypervisor_mode: kvm

# Nova metadata port
nova_metadata_port: 8775

# Nova database details
nova_db_name: nova
nova_api_db_name: nova_api
nova_db_user: nova
nova_db_pass: "!nova!"

## Nova Service Auth
nova_service_name: nova
nova_service_region: RegionOne
nova_service_project_name: service
nova_service_project_domain_id: default
nova_service_user_domain_id: default
nova_service_user_name: nova
nova_service_user_pass: nova_pass
nova_service_role_name: admin

nova_system_user: nova
nova_system_group: nova

# Nova control plane yum packges
nova_control_plane_yum_packages:
  - openstack-nova-api
  - openstack-nova-conductor
  - openstack-nova-console
  - openstack-nova-novncproxy
  - openstack-nova-scheduler

nova_control_plane_services:
  - openstack-nova-api
  - openstack-nova-conductor
  - openstack-nova-consoleauth
  - openstack-nova-novncproxy
  - openstack-nova-scheduler

# Nova compute packages
nova_compute_yum_packages:
  - openstack-nova-compute

nova_compute_services:
  - openstack-nova-compute
  - libvirtd

## RabbitMQ info
nova_rabbitmq_user: nova
nova_rabbitmq_pass: nova
nova_rabbitmq_vhost: /nova

# Nova ceph details
nova_ceph_pool: vms
nova_ceph_client: "{{ cinder_ceph_client }}"
nova_ceph_uuid: "{{ ceph_uuid }}"

