---
# Copyright 2016, Stackmasters.eu

- name: Create fernet keys for Keystone
  command: keystone-manage fernet_setup --keystone-user "{{ keystone_system_user_name }}" --keystone-group "{{ keystone_system_group_name }}"
  notify: Restart apache
  when: inventory_hostname == groups['keystone'][0]
  tags:
    - keystone-fernet

- name: Fetch tokens from first host
  fetch:
    src: /etc/keystone/fernet-keys/{{ item }}
    dest: /tmp/fernet-keys/{{ item }}
    fail_on_missing: no
  with_items:
    - 0
    - 1
  when: inventory_hostname == groups['keystone'][0]
  tags:
    - keystone-fernet

- name: Drop tokens on all other hosts
  copy:
    src: /tmp/fernet-keys
    dest:  /etc/keystone/fernet-keys
    directory_mode: yes
    owner: keystone
    group: keystone
    mode: 0600
  when: inventory_hostname != groups['keystone'][0]
  tags:
    - keystone-fernet
