---
# Copyright 2016, Stackmasters.eu

- name: Create the service entity for keystone
  shell: openstack service create \
            --name {{ keystone_service_name }} \
            --os-token {{ keystone_admin_token }} \
            --os-url {{ keystone_os_url }} \
            --os-identity-api-version {{ keystone_os_identity_api_version }} \
            --description "OpenStack Identity" identity

- name: Create keystone service API endpoints
  shell: openstack endpoint create \
            --region {{ keystone_service_region }} \
            --os-token {{ keystone_admin_token }} \
            --os-identity-api-version {{ keystone_os_identity_api_version }} \
            --os-url {{ keystone_os_url }} identity {{ item }} http://{{ internal_vip }}:5000/v3
  with_items:
    - public
    - internal

- name: Create keystone service API admin endpoint
  shell: openstack endpoint create \
            --region {{ keystone_service_region }} \
            --os-token {{ keystone_admin_token }} \
            --os-identity-api-version {{ keystone_os_identity_api_version }} \
            --os-url {{ keystone_os_url }} identity admin http://{{ internal_vip }}:35357/v3

- name: Create the default domain
  shell: 'openstack domain create \
            --os-token {{ keystone_admin_token }} --os-url {{ keystone_os_url }} \
            --os-identity-api-version {{ keystone_os_identity_api_version }} \
            --description "Default Domain" {{ keystone_service_project_domain_id }}'

- name: Create the admin project
  shell: openstack project create --domain default \
           --os-identity-api-version {{ keystone_os_identity_api_version }} \
           --os-token {{ keystone_admin_token }} --os-url {{ keystone_os_url }} \
           --description "Admin Project" {{ keystone_admin_project }}

- name: Create the service project
  shell: openstack project create --domain default \
           --os-identity-api-version {{ keystone_os_identity_api_version }} \
           --os-token {{ keystone_admin_token }} --os-url {{ keystone_os_url }} \
           --description "Service Project" {{ keystone_service_project }}

- name: Create the admin user
  shell: openstack user create --domain default \
           --os-identity-api-version {{ keystone_os_identity_api_version }} \
           --os-token {{ keystone_admin_token }} --os-url {{ keystone_os_url }} \
           admin

- name: Create admin role
  shell: openstack role create \
           --os-identity-api-version {{ keystone_os_identity_api_version }} \
           --os-token {{ keystone_admin_token }} --os-url {{ keystone_os_url }} \
           admin

- name: Assign admin role to admin user
  shell: openstack role add --project admin --user admin \
            --os-token {{ keystone_admin_token }} \
            --os-url {{ keystone_os_url }} \
            --os-identity-api-version {{ keystone_os_identity_api_version }} \
            admin
