---
# Copyright 2016, Stackmasters.eu

- name: Start Keystone service
  service:
    name: httpd
    state: started
    enabled: true
  tags:
    - keystone-config
    - keystone-apache-configuration

- name: Bootstrap keystone admin and endpoint
  command: |
     /usr/bin/keystone-manage bootstrap \
     --bootstrap-username {{ keystone_admin_user }} \
     --bootstrap-password {{ keystone_admin_user_password }} \
     --bootstrap-project-name {{ keystone_admin_project }} \
     --bootstrap-role-name {{ keystone_admin_role }} \
     --bootstrap-service-name {{ keystone_service_name }} \
     --bootstrap-region-id {{ keystone_service_region }} \
     --bootstrap-admin-url {{ keystone_os_url }} \
     --bootstrap-public-url http://192.168.110.1:5000/v3 \
     --bootstrap-internal-url http://192.168.110.1:5000/v3
  become: yes
  become_user: "{{ keystone_system_user_name }}"
  changed_when: false
  register: add_service
  until: add_service|success
  tags:
    - keystone-bootstrap

- name: Check if Keystone service project is present
  shell: source /root/openrc && openstack project list
  register: service_project
  tags:
    - keystone-service

- name: Create the service project
  shell: source /root/openrc && openstack project create --description "Service Project" {{ keystone_service_project }}
  when: "service_project.stdout.find('service') == -1"
  tags:
    - keystone-service
