---
# Copyright 2016, Stackmasters.eu

- include: role-pre-install.yml
- include: role-install-centos.yml
  when: "ansible_os_family == 'RedHat'"
- include: role-install-ubuntu.yml
  when: "ansible_os_family == 'Debian'"
- include: role-post-install.yml
