---
# Copyright 2016, Stackmasters.eu

# Neutron database name:
neutron_db_name: neutron
neutron_db_user: neutron
neutron_db_pass: "!neutron!"

# Neutron unix account details
neutron_system_user: neutron
neutron_system_group: neutron

# Neutron service details
neutron_service_region: RegionOne
neutron_service_user_name: neutron
neutron_service_user_pass: neutron_pass
neutron_service_role_name: "admin"
neutron_service_project_domain_id: default
neutron_service_user_domain_id: default
neutron_service_project_name: "service"
neutron_metadata_agent_secret: secret

# Enable neutron dvr mode
neutron_dvr: False

# Neutron controller node packages
neutron_control_plane_yum_packages:
  - openstack-neutron
  - openstack-neutron-ml2
  - openstack-neutron-openvswitch
  - ebtables

# Nuetron compute node packages
neutron_agents_yum_packages:
  - openstack-neutron-openvswitch
  - ebtables
  - ipset

## RabbitMQ info
neutron_rabbitmq_user: neutron
neutron_rabbitmq_pass: neutron
neutron_rabbitmq_vhost: /neutron

neutron_provider_networks:
  network_mappings: "flat:br-ex" 

# Neutron Plugins
neutron_plugin_type: ml2.ovs

# Types of networks supported by the ml2 plugin
neutron_ml2_drivers_type: "flat,vxlan"

# Enable or disable L2 Population.
neutron_l2_population: "False"

neutron_plugins:
  ml2.lxb:
    driver_firewall: neutron.agent.linux.iptables_firewall.IptablesFirewallDriver
    driver_interface: neutron.agent.linux.interface.BridgeInterfaceDriver
    drivers_type: "{{ neutron_ml2_drivers_type }}"
    l2_population: "{{ neutron_l2_population }}"
    mechanisms: "linuxbridge,l2population"
    plugin_core: neutron.plugins.ml2.plugin.Ml2Plugin
    plugin_ini: plugins/ml2/ml2_conf.ini
    network_mappings: "flat:br-ex,vxlan:br-vxlan" 
  ml2.ovs:
    driver_firewall: neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
    driver_interface: neutron.agent.linux.interface.OVSInterfaceDriver
    drivers_type: "{{ neutron_ml2_drivers_type }}"
    l2_population: "{{ neutron_l2_population }}"
    mechanisms: "openvswitch,l2population"
    plugin_core: neutron.plugins.ml2.plugin.Ml2Plugin
    plugin_ini: plugins/ml2/ml2_conf.ini
    network_mappings: "flat:br-ex" 

# Define the linux ml2 mechanism
neutron_ml2_mechanism_driver: "linuxbridge,l2population"

# Neutron dhcp agents per network config
neutron_dhcp_agents_per_network: 1

## RabbitMQ info
neutron_rabbitmq_userid: neutron
neutron_rabbitmq_pass: neutron
neutron_rabbitmq_vhost: /neutron


# Neutron services
neutron_services:
 neutron-dhcp-agent:
   group: neutron_control
   service_name: neutron-dhcp-agent
   service_en: True
   service_conf: dhcp_agent.ini
   service_group: neutron_agent
 neutron-openvswitch-agent:
   group: neutron_agents
   service_name: neutron-openvswitch-agent
   service_en: "{{ neutron_plugin_type == 'ml2.ovs' }}"
   service_conf: plugins/ml2/openvswitch_agent.ini
   service_group: neutron_openvswitch_agent
 neutron-linuxbridge-agent:
   group: neutron_agents
   service_name: neutron-linuxbridge-agent
   service_en: "{{ neutron_plugin_type == 'ml2.lxb' }}"
   service_conf: plugins/ml2/linuxbridge_agent.ini
   service_group: neutron_linuxbridge_agent
 neutron-metadata-agent:
   group: neutron_control
   service_name: neutron-metadata-agent
   service_en: True
   service_conf: metadata_agent.ini
   service_group: neutron_agent
 neutron-server:
   group: neutron_control
   service_name: neutron-server
   service_en: True
   service_group: neutron_server
 neutron-l3-agent:
   group: neutron_agents
   service_name: neutron-l3-agent
   service_en: True
   service_conf: l3_agent.ini
   service_group: neutron_server

