---
# Copyright 2016, Stackmasters.eu

- name: Install Openstack Mitaka repo
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-openstack-mitaka

- name: Install openstackclient
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-openstackclient

- name: Drop openrc file
  template:
    src: openrc.j2
    dest: /root/openrc
    owner: root
    group: root
    mode: "0600"
  tags:
    - openstack-openrc-file
