---
# Copyright 2016, Stackmasters.eu

- name: Create neutron database
  mysql_db:
    name: "{{item}}"
    state: present
    login_host: "{{ groups['galera'][0] }}"
    login_user: root
    login_password: "{{ galera_root_pass }}"
  with_items:
    - "{{ neutron_db_name }}"
  tags:
    - neutron-db-setup

- name: Create neutron db user
  mysql_user:
    state: present
    name: "{{ neutron_db_user }}"
    host: "{{ item }}"
    priv: "{{ neutron_db_name }}.*:ALL"
    password: "{{ neutron_db_pass }}"
    login_host: "{{ groups['galera'][0] }}"
    login_user: root
    login_password: "{{ galera_root_pass }}"
  with_items:
    - "localhost"
    - "%"
  tags:
    - neutron-db-setup

- name: Perform a Neutron DB sync
  shell: "neutron-db-manage --config-file /etc/neutron/neutron.conf \
  --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head"
  sudo: yes
  sudo_user: "{{ neutron_system_user }}"
  tags:
    - neutron-db-setup
    - neutron-setup
    - neutron-db-sync
