---
# Copyright 2016, Stackmasters.eu

- name: Drop chrony config
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: chrony
    group: chrony
    mode: "0644"
  notify: restart chronyd
  tags:
    - openstack-ntp
