---
# Copyright 2016, Stackmasters.eu

- name: Drop chrony config
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0600"
  tags:
    - openstack-ntp
