---
# Copyright 2016, Stackmasters.eu

- name: Install support packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ os_support_packages }}"

- name: Restart network
  service:
    name: network
    state: restarted
    enabled: yes
